---
- name: HashiCorp Vault Lookup Example
  hosts: all
  tasks:
    - name: Retrieve a KV Secret from HashiCorp Vault
      debug:
        msg: "My RHEL Version stored in Vault is {{ vaultkv_secret }}"
